### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by Liuchangjin123** [SonSang/diff-hybrid-traffic-sim#1]
Hello, I'm just starting to learn this topic. Could you please guide me on how to run this code? Thank you!

**Comment by SonSang** [comment]
Hi, thank you for the question.
You can install the prerequisites in the README, and then run some experiments using the commands there.
For instance, you can run experiments to solve inverse problem using command like below:

python example/inverse/macro.py
python example/inverse/micro.py
python example/inverse/hybrid.py 

Thank you.
